python3 -W ignore amc_fine_tune.py \
    --model=mobilenet \
    --dataset=imagenet \
    --lr=0.05 \
    --n_gpu=1 \
    --batch_size=256 \
    --n_worker=32 \
    --lr_type=cos \
    --n_epoch=100 \
    --wd=4e-5 \
    --seed=2018 \
    --data_root=/srv/datasets \
    --ckpt_path=./logs/mobilenet_imagenet_q_search-run99/model_best_quantized.pth
